name: basic-service
image_uri: 'anyscale/ray:2.39.0-slim-py312'
compute_config: 'small-head-node-only:2'
cloud: {{ vars.CLOUD_NAME}}
ray_version: 2.39.0
query_auth_token_enabled: false
applications:
  - name: basic-hola-service
    import_path: 'main:my_app'
    runtime_env:
      pip: []
      working_dir: .
    route_prefix: /

# anyscale service deploy -f service.yaml